before_script:
    - echo "--------------------------------"
    #- ARDUINO_VERSION="arduino-1.8.5"
    - ARDUINO_PATH="/arduino/"
    - pwd
    - WD=$(pwd)
    - export PATH=$WD/buildroot/bin/:$ARDUINO_PATH:$PATH
    - mkdir build -p -v
    #- echo "--------------------------------"

build:
    script:
        - build_marlin
        - pwd
        - cd buildroot
        - ls

    artifacts:
        name: "marlin-bvc-$CI_COMMIT_REF_NAME"
        paths:
            - build/*.hex
        expire_in: 1 week
